-- Standard Function 표준 함수

-- DUAL Table   : 가상 테이블 -> 결과 확인용 Table
SELECT 1 FROM DUAL;
SELECT 'A' FROM DUAL;
SELECT '가' FROM DUAL;
SELECT 23 * 45 FROM DUAL;

-- 문자 함수
-- CHR(N)  ASCII값을 문자로 변환 cf) N은 숫자
SELECT CHR(65) FROM DUAL;
SELECT CHR(97) FROM DUAL;

-- ASCII <-> CHR
SELECT ASCII('A') FROM DUAL;
SELECT ASCII('a') FROM DUAL;

-- "안녕하세요" + "건강하세요" = "안녕하세요건강하세요"
-- OR가 아닌   ||        붙여쓰기
SELECT '내 점수는 ' || CHR(65) || '입니다' FROM DUAL;

--LPAD(RPAD) : 나머지를 빈칸(지정문자)으로 채운다.
SELECT LPAD('BBB', 10) FROM DUAL;
SELECT RPAD('BBB', 10) FROM DUAL;
SELECT LPAD('BBB', 10, '-') FROM DUAL;
SELECT LPAD('123', 10, '0') FROM DUAL;

-- 번지수 찾기 INSTR == indexOf('a') defande 3이 나왔었음
select instr('123ABC456DEF', 'A') FROM DUAL; -- DB는 0번지 없음
select instr('123ABC456DEFABC', 'A', 7) FROM DUAL; -- 7번째 이후 A
select instr('123ABC456DEFABCABC', 'A', 7, 2) FROM DUAL; --7번째 이후 2번째 A
select instr('123ABC456DEF', 'Y') FROM DUAL; -- 못찾으면 0이 나옴

-- REPLACE : 문자열 치환
SELECT REPLACE('AAAAABCD', 'A') FROM DUAL; --A를 빈 문자로
SELECT REPLACE('AAAAABCD', 'A', 'a') FROM DUAL; --A가 a로 바뀜
SELECT REPLACE('AAAAABCD', 'AA', 'a') FROM DUAL;

-- TRANSLATE : 문자 치환
SELECT TRANSLATE('AAAAABCD', 'A', 'a') FROM DUAL; 
SELECT TRANSLATE('AAAAABCD', 'AA', 'a') FROM DUAL; --AA라고 적어도 A앞만 받음
SELECT TRANSLATE('AAAAABCD', 'AB', 'a') FROM DUAL; --AB라 적었을때 

-- 숫자
-- 올림
SELECT CEIL(13.1) FROM DUAL;
-- 내림
SELECT FLOOR(13.9) FROM DUAL;
-- 나눈 나머지
SELECT MOD(3,2) FROM DUAL;
-- 승수
SELECT POWER(3,2) FROM DUAL;
-- 반올림
SELECT ROUND(13.5) FROM DUAL;
-- 버림
SELECT TRUNC(12.3456) FROM DUAL; --정수 값만
SELECT TRUNC(12.3456, 2) FROM DUAL;
SELECT TRUNC(12.3456, -1) FROM DUAL;

-- SIGN(부호 +:1 0:0 -:-1 ) 부호만 리턴
SELECT SIGN(13.4) FROM DUAL;
SELECT SIGN(0) FROM DUAL;
SELECT SIGN(-12) FROM DUAL;


-- 변환 함수
-- TO_CHAR 
-- DATE -> VARCHAR2
SELECT TO_CHAR(SYSDATE)
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD-HH-MI-SS')
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD/ HH:MI:SS')
FROM DUAL;

SELECT TO_CHAR(100000000000, '$999,999,999,999')
FROM DUAL;

-- TO_DATE
-- VARCHAR2 -> DATE
SELECT TO_DATE('20200617') 
FROM DUAL;

SELECT TO_DATE('20201225', 'YYYYMMDD') 
FROM DUAL;

SELECT TO_DATE('12252020', 'MMDDYYYY')
FROM DUAL;

-- TO_NUMBER    VARCHAR2 -> NUMPER parseInt()
SELECT TO_NUMBER('123') + 12
FROM DUAL;

-- LAST_DAY
SELECT LAST_DAY('20/06/01')
FROM DUAL;

SELECT LAST_DAY( TO_DATE('200601', 'YYMMDD') )
FROM DUAL;              --20-06-01 에러남 형식이 달라

-- SUBSTR 1번지는 1 /cf)substring(1,2)"ABCDE" -> BC  index개념 0부터 시작하는 java
SELECT SUBSTR('ABCDE', 3) -- 3번지부터 끝까지
FROM DUAL; --CDE

SELECT SUBSTR('ABCDE', 3, 2) -- 3번지부터 2개
FROM DUAL; --CD
