DROP TABLE CAFE
CASCADE CONSTRAINTS;	
DROP TABLE CUSTOMER
CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER(
	ID VARCHAR2(30),
	PWD VARCHAR2(30) NOT NULL,
	NAME VARCHAR2(30) NOT NULL,
	CUGE VARCHAR2(30) NOT NULL,
	CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID) 
);


CREATE TABLE CAFE(
	ID VARCHAR2(30),
	COFFEE VARCHAR2(30) NOT NULL,
	CUPSIZE VARCHAR2(30) NOT NULL,
	ADDSYRP VARCHAR2(30),
	ADDSHOT VARCHAR2(1),
	ADDWHIP	VARCHAR2(1),
	CUPS VARCHAR2(5),
	PRICE VARCHAR2(30),
	CONSTRAINT FK_CAFE FOREIGN KEY(ID)
	REFERENCES CUSTOMER(ID)
);

DELETE FROM CAFE
WHERE ID IS NULL;

INSERT INTO CAFE
VALUES(100, '기획부', 20, 200);